In [1]:
#Setup
from sklearn import svm, metrics
from sklearn import preprocessing
import matplotlib.pyplot as plt

In [2]:
#Task 1

#Import MNIST dataset (code from Deep Learning with Python textbook)
from keras.datasets import mnist
(train_x, train_y), (test_x, test_y) = mnist.load_data()
train_x = train_x/255.0
test_x = test_x/255.0
train_x = train_x.reshape((train_x.shape[0],-1))
test_x = test_x.reshape((test_x.shape[0],-1))

train_x = preprocessing.scale(train_x)
test_x = preprocessing.scale(test_x)

var = svm.SVC(C = 0.1, kernel = 'linear', gamma='scale')
var.fit(train_x, train_y)
p = var.predict(test_x)

acc = metrics.accuracy_score(test_y, p)
confusion = metrics.confusion_matrix(test_y, p)
print("Accuracy = ", acc*100, "%")
print(confusion)

11493376/11490434 [==============================] - 0s 0us/step
Accuracy =  93.76 %
[[ 958    0    5    2    1    7    5    1    1    0]
 [   0 1117    6    3    0    1    3    1    4    0]
 [   6   10  966   12    5    4    7    7   15    0]
 [   4    0   16  950    1   14    2    5   14    4]
 [   2    2   10    1  937    0    5    4    4   17]
 [   8    3    4   41    5  797   12    1   19    2]
 [  13    4   13    1    7   18  900    0    2    0]
 [   1    8   21   12    7    0    0  959    0   20]
 [   7    6    7   25    7   24    7    8  873   10]
 [   9    6    3    8   28    5    0   22    9  919]]


-----**Task 2**----- 

Given features: $(x_{1},y_{1}),...,(x_{N},y_{N})$ where $y_{1},...,y_{N}∈\left \{ -1,1 \right \}$ <br>
Minimize: $w^{T}\cdot w+C\sum_{i=1}^{N}\xi _{i}$ <br> 
> (1) *subject to:* $y_{i}\cdot \left ( w^{T}\cdot x_{i} \right )\geq 1-\xi_{i}$ <br>
> (2) *and* $\xi_{i}\geq 0$ for $i= 1,...,N$<br>

We can deduce from the SVM lecture slides, the following **primal margin**:
> Primal Margin: $\gamma = \frac{1}{\sqrt{w^{T}\cdot w + C\sum_{i=1}^{N}\xi _{i}}}$

The Lagrange function given our constraints and functions will be in the following form: <br>
> $L=\frac{1}{2}w^{T}\cdot w + C\sum_{i=1}^{N}\xi _{i} + \sum _{i} \mu (1-y_{i}w^{T}x_{i} - \xi _{i}) - \sum_{i=1}^{N}\lambda _{i}\xi _{i}$
<br>Lagrange Multipliers: $\mu\geq 0$ and $\lambda\geq 0$

Claim:<br>
> $\underset{\mu ,\lambda }{max}\underset{w,\xi }{min} L\leq \underset{w,\xi }{min} \underset{\mu ,\lambda }{max}L $

Expanding Lagrange function:
>$L=\frac{1}{2}w^{T}\cdot w + C\sum_{i=1}^{N}\xi _{i}+\sum _{i}\mu _{i} - \sum _{i}\mu _{i}y_{i}w^{T}x_{i} - \sum _{i}\mu _{i}\xi _{i} - \sum_{i=1}^{N}\lambda _{i}\xi _{i}$<br>

Taking the derivative of the function:
> $\tfrac{\partial L}{\partial w} = w - \sum _{i}\mu _{i}y_{i}x_{i}=0\Rightarrow w = \sum _{i}\mu _{i}y_{i}\overrightarrow{x_{i}}$<br>
$\tfrac{\partial L}{\partial \xi } = C - \mu _{i} - \lambda _{i} = 0 \Rightarrow C = \mu _{i}+\lambda_{i} $<br>

Substituting $w = \sum _{i}\mu _{i}y_{i}\overrightarrow{x_{i}}$ and $C = \mu _{i}+\lambda_{i}$ into Lagrange function, we get the dual problem of
maximizing:
> $L=\frac{1}{2}w^{T}\sum _{i}\mu _{i}y_{i}\overrightarrow{x_{i}} + \left ( \mu _{i}+\lambda_{i} \right )\sum_{i=1}^{N}\xi _{i}+\sum _{i}\mu _{i} - \sum _{i}w^{T}\mu _{i}y_{i}x_{i} - \sum _{i}\mu _{i}\xi _{i} - \sum_{i=1}^{N}\lambda _{i}\xi _{i}$<br>
$L=\sum _{i}\mu _{i}-\frac{1}{2}w^{T}\sum _{i}\mu _{i}u_{i}\overrightarrow{x_{i}}$<br>
$L=\sum _{i}\mu _{i}-\frac{1}{2}\sum _{i,j}\mu _{i}\mu _{j}y_{i}y_{j}(\overrightarrow{x_{i}}x_{j})$

The **dual margin** is: 
>$\gamma=\frac{1}{\sqrt{\mu _{i}\mu _{j}y_{i}y_{j}(\overrightarrow{x_{i}}x_{j})}}$<br>

**Summary**:<br>
> Primal Margin: $\gamma = \frac{1}{\sqrt{w^{T}\cdot w + C\sum_{i=1}^{N}\xi _{i}}}$<br>
Dual Margin: $\gamma=\frac{1}{\sqrt{\mu _{i}\mu _{j}y_{i}y_{j}(\overrightarrow{x_{i}}x_{j})}}$<br>







**Benefits of maximizing the margin:**<br>
* Maximizing the margin helps avoid the overfitting problem. <br>

**Characterize the support vectors:**<br>
There are three possibilities:
1. Support vectors are lying on the wrong side of the hyperplane $\xi _{n}\geq 1$
2. Support vectors are lying within the margin boundaries $\left ( 0< \xi _{n}< 1 \right )$ but still on the correct side 
3. Support vectors are lying on the margin boundaries $\left (\xi _{n}=0  \right )$<br>

**Point out the benefit of solving the dual problem instead of the primal problem:**<br>
* The dual problem provides a lower bound of the primal problem 


